.PHONY: all clean install tags 
# order matters, at least db-basic-ilf-rest
TCLFILES=\
tcllib/entry.tcl \
tcllib/db.tcl \
tcllib/basic.tcl \
tcllib/ilf.tcl \
tcllib/control.tcl \
tcllib/csv.tcl \
tcllib/gui.tcl \
tcllib/bibtex.tcl \
tcllib/html.tcl \
tcllib/memo.tcl \
tcllib/nlm.tcl \
tcllib/rtf.tcl \
tcllib/tex.tcl 

TODAY=`date +"%Y-%m-%d"`
BASETCLFILES=$(TCLFILES:tcllib/%=%)

all: tcllib/pkgIndex.tcl tclbib_compressed.tcl

tclbib_compressed.tcl: tclbib.tcl $(TCLFILES)
	echo '#!/bin/sh' > $@
	echo '# tclbib (c) F.A. Meineke 1997-2004, revised 2024' >> $@
	echo '# This file is generated. Do not edit this file!' >> $@
	echo '# The next line restarts using wish \\' >> $@ 
	echo 'exec wish "$$0" "$$@"' >> $@
	cat $(TCLFILES) tclbib.tcl | sed \
	    -e 's/^	*//' \
	    -e 's/\([^[]\)	\+/\1 /g' \
	    -e 's/^ *//' \
	    -e 's/^#.*//' \
	    -e 's/;#.*//' \
	    -e 's/ *$$//' \
	    -e 's/^lappend auto_path.*//' \
	    -e 's/^exec wish.*//' \
	    -e '/^$$/d' \
	    -e "s/^set version .*/set version \"${TODAY}\"/"  >> $@
	chmod +x tclbib_compressed.tcl
	
tcllib/pkgIndex.tcl: $(TCLFILES)
	(cd tcllib; echo "pkg_mkIndex . ${BASETCLFILES} "| tclsh)
	
install: all
	cp -u tclbib_compressed.tcl $(HOME)/bin/tclbib.tcl

clean:
	rm -f tclbib_compressed.tcl *.il[1-4] tcllib/pkgIndex.tcl

