# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded Basic 1.0 [list source [file join $dir basic.tcl]]
package ifneeded BibTeX 1.0 [list source [file join $dir bibtex.tcl]]
package ifneeded Control 1.0 [list source [file join $dir control.tcl]]
package ifneeded Csv 1.0 [list source [file join $dir csv.tcl]]
package ifneeded Db 1.0 [list source [file join $dir db.tcl]]
package ifneeded Entry 1.0 [list source [file join $dir entry.tcl]]
package ifneeded Gui 1.0 [list source [file join $dir gui.tcl]]
package ifneeded Html 1.0 [list source [file join $dir html.tcl]]
package ifneeded Ilf 1.0 [list source [file join $dir ilf.tcl]]
package ifneeded Memo 1.0 [list source [file join $dir memo.tcl]]
package ifneeded Nlm 1.0 [list source [file join $dir nlm.tcl]]
package ifneeded Rtf 1.0 [list source [file join $dir rtf.tcl]]
package ifneeded TeX 1.0 [list source [file join $dir tex.tcl]]
